### ISSUE TITLE
Improve filter creation experience

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#21]
1) The section "Filtrování tržiště" should have 3 buttons which select what to filter
Ignorovat úvěr, Ignorovat participaci, Ignorovat vše -> remove filtered item dropdown from the modal.
Maybe put those in the accordion heading.

2) The modal should have 3 buttons:
Uložit
Přidat výjimku >> / << Zpět
Zrušit

**Comment by jhrcek** [comment]
Improvement implemented https://github.com/RoboZonky/natural-strategy-setup/commit/75f2e07449186971bc72962a16124c9e6b697f7f and deployed. @triceo check it and let me know if it's ok. The only thing that I didn't implement was putting the 3 buttons "Ignorovat ..." into accordion heading, because it looked bad.

**Comment by triceo** [comment]
- The button to add an exception is very pronounced, and I would click on the "Save" button instead. First, I'd put it to the end, also I'd give it another color. Green?
- You might want to rename the buttons to add filters. I would see it in "ǘvěr" / "participaci" / "obojí", where there would be some text "Přidat filtr pro:" before these buttons.

Otherwise looks good!

**Comment by jhrcek** [comment]
Suggestions implemented https://github.com/RoboZonky/natural-strategy-setup/commit/446ad7a5d5b29d098a20042b06ee2f31f6993370

**Comment by triceo** [comment]
Looks good!
