### ISSUE TITLE
Remove the range sliders from portfolio structure.

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#65]
Future versions of _RoboZonky_ will no longer support rating share ranges. More specifically, they will only support the high end of the range.

In practice:

`Prostředky úročené 2,99 % p.a. mají tvořit 3 až 43 % aktuální zůstatkové částky.`

becomes:

`Prostředky úročené 2,99 % p.a. mají tvořit 43 % aktuální zůstatkové částky.`

We should enforce the minimum sum of 100 %. And we could add a warning if it goes over 100 %, but that's not necessarily a problem.

In terms of _RoboZonky_ behavior, this doesn't change anything. The lower end of the range appears to have lost any actual meaning in the code years ago.

There is no rush, @jhrcek. We will deploy the change without doing a new release of _RoboZonky_.

Here's the upstream change removing the ranges from robozonky: https://github.com/RoboZonky/robozonky/pull/470

**Comment by jhrcek** [comment]
Ok, I'll work on this in the next few days. Is robozonky going to become less tolerant in what it can parse? Will it still be able to parse older strategies "x až y", or will minimum required robozonky version/strategy version for restoring from URL need to be bumped?

**Comment by triceo** [comment]
@jhrcek The robot will continue supporting it, but it will show a warning. Some future version (not 5.6) will remove it completely.
I don't think we need to bump the minimum required version.
And yes, the existing upper bound will do just fine.

**Comment by jhrcek** [comment]
I started working on it and have some questions about when/what warnings to show

1. when restoring strategy from url should I ...
a) always show warning ala "vaše strategie má starý formát struktury portfolia, který byl změněn bla bla viz [link na dokument o zmenach strategie]"
b) show warning only when user had lower bound != upper bound for some rating?
c) don't show any warning, just go with the upper bound s/he had

2. when editing portfolio structure
a) show error (= and don't render strategy because it's invalid) when the sum < 100
b) show warning when the sum exceeds 100 "součet podílů přesahuje 100%. To není nezbytně problém, ale může to způsobit nepředvídatelnost struktury portfolia. Proto doporučujeme dosáhnout součtu 100%" - not sure what how to motivate "it's better to try to reach sum of 100 :-)

**Comment by triceo** [comment]
My opinion:

1. b) 
2. definitely an error when < 100 %. if over > 100 %, the warning should be enough.

When it comes to the motivation for why 100 % is the best... If you say "up to 50 % in D-rated", the robot can do just that. In fact, anything where the sum is over 100 % effectively means "more or less random".
